### PR TITLE
Added visualize.R, updated Rmd and ipynb

### PR DESCRIPTION
**Pull request by berkaytacar**
- Added visualize.R to deal with distribution visualization
- Used the function in Rmd and ipynb
- Open to suggestions for testing?

Waiting for feedback @emiliodg @RayNguyent @rhysong

### CODE REVIEW

**Comment by berkaytacar** [comment]
Attached it to the Project Board as well #9

**Comment by RayNguyent** [comment]
looks good to me

**Comment by RayNguyent** [comment]
i think u can test on the title

**Review by rhysong — APPROVED** [review]
Looks good! Test case could include a simple check for the labels and title. TA did mention a way to test graphs but we might need to look more into it

**Comment by berkaytacar** [comment]
> looks good to me. Actually, u can comment out `library(ggplot2)` because will run that at the beginning of the report, and i think u need to add specification to your function as well

Fixed.

**Comment by berkaytacar** [comment]
Merging this!

**Pull request merged**
